FROM node:20-alpine

WORKDIR /app

COPY volkanagram-web/package*.json ./

RUN npm ci

COPY volkanagram-web/ .
COPY .env.production .env.local

RUN npm run build
RUN npm prune --omit=dev

EXPOSE 3000

CMD ["npm", "start"]